name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar:
    runs-on: windows-latest  # Use Windows runner instead of Ubuntu

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Install .NET Framework Developer Pack
        run: |
          choco install dotnetfx -y
          choco install dotnetfx-sdk -y
          choco install visualstudio2019buildtools --package-parameters "--add Microsoft.Net.Component.4.8.SDK --add Microsoft.VisualStudio.Component.Web --includeRecommended" -y

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Solution
        run: dotnet build --no-restore

      - name: Install SonarScanner for .NET
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Begin SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          dotnet-sonarscanner begin /k:"your-project-key" `
            /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}" `
            /d:sonar.login="${{ secrets.SONAR_TOKEN }}" `
            /d:sonar.cs.opencover.reportsPaths="coverage.opencover.xml"

      - name: Build Solution for Analysis
        run: dotnet build --no-restore

      - name: Run Unit Tests & Collect Coverage
        run: |
          dotnet test --no-build --collect:"XPlat Code Coverage" `
            --settings coverlet.runsettings

      - name: End SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
